name: Continuous Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest


    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Make run-migrations.sh executable
        run: chmod +x run-migrations.sh

      - name: Run migrations
        run: ./run-migrations.sh