name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches: 
      - main
  workflow_dispatch:  # Add this to allow manual triggers

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}

    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy orbat \
          --source . \
          --region europe-central2 \
          --timeout 300 \
          --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}",GCS_BUCKET_NAME="${{ secrets.GCS_BUCKET_NAME }}" \
          --project ${{ secrets.GCP_PROJECT_ID }}
        gcloud run services add-iam-policy-binding orbat \
          --region=europe-central2 \
          --member=allUsers \
          --role=roles/run.invoker