name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy orbat \
          --source . \
          --region europe-central2 \
          --allow-unauthenticated \
          --timeout 300 \
          --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          --project ${{ secrets.GCP_PROJECT_ID }}