name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
         gcloud run deploy orbat \                           
          --source . \                                                                    
          --region europe-central2 \                   
          --allow-unauthenticated \
          --timeout 300 \
          --set-env-vars DATABASE_URL="libsql://orbat-db-dontwanttorevealname.turso.io?authToken=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzg3NjEwNDEsImlkIjoiN2ZiODA0ZjktMzZhZC00M2ViLWI1ZDQtZDYxODg0YTYwNjE0In0.031CrsCX2HtB5ZPZoICKLZCBoFZU2cCZvweIzg3w97s7kMhbFhK-2k3ECbyc0K5pLrOcaGjpdOWdnk8qc3NgBg"