name: Test and Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Create .env.test file
        run: |
          echo "DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}" > .env.test
          echo "GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}" >> .env.test
          echo "GOOGLE_APPLICATION_CREDENTIALS=credentials.json" >> .env.test

      - name: Install dependencies
        run: go mod download

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Make scripts executable
        run: |
          chmod +x run-test-migrations.sh
          chmod +x run-migrations.sh

      - name: Setup test database and run migrations
        run: |
          ./run-test-migrations.sh

      - name: Start application in test mode
        run: |
          ENV=test go run main.go &
          # Store the PID of the application
          echo $! > .app.pid
          # Wait for the application to start by polling the endpoint
          timeout 30s bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 1; done'

      - name: Install Playwright dependencies
        run: |
          go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps
          # Install xvfb for any potential headed browser needs
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run tests
        env:
          CI: true  # This will trigger headless mode in the integration tests
        run: |
          go test ./... -v
          xvfb-run --auto-servernum go test ./tests/integration -v

      - name: Cleanup
        if: always()
        run: |
          # Kill the application if it's still running
          if [ -f .app.pid ]; then
            kill $(cat .app.pid) || true
            rm .app.pid
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/*_test.go
            **/testdata
            tests/integration/test-results
          retention-days: 7

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}

    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy orbat \
          --source . \
          --region europe-central2 \
          --timeout 300 \
          --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}",GCS_BUCKET_NAME="${{ secrets.GCS_BUCKET_NAME }}" \
          --project ${{ secrets.GCP_PROJECT_ID }}
        gcloud run services add-iam-policy-binding orbat \
          --region=europe-central2 \
          --member=allUsers \
          --role=roles/run.invoker