name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Make test script executable
        run: chmod +x run-test-migrations.sh

      - name: Setup test database
        run: ./run-test-migrations.sh
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

      - name: Run tests
        run: go test ./... -v
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/*_test.go
            **/testdata
          retention-days: 7